if(EXISTS "/home/mzy/Code/googletest-demo/bulid/hello_test[1]_tests.cmake")
  include("/home/mzy/Code/googletest-demo/bulid/hello_test[1]_tests.cmake")
else()
  add_test(hello_test_NOT_BUILT hello_test_NOT_BUILT)
endif()
