if(EXISTS "/home/mzy/Code/googletest-demo/bulid/queue/queue_test[1]_tests.cmake")
  include("/home/mzy/Code/googletest-demo/bulid/queue/queue_test[1]_tests.cmake")
else()
  add_test(queue_test_NOT_BUILT queue_test_NOT_BUILT)
endif()
